//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FamilyTree.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Couple
    {
        public int coupleID { get; set; }
        public int NumberOfChildren { get; set; }
        public int personOne { get; set; }
        public int personTwo { get; set; }
    }
}
